// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TestEntity
{
	private final IMendixObject testEntityMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.TestEntity";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Age("Age"),
		TestEntity_SecondEntity("MyFirstModule.TestEntity_SecondEntity");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TestEntity(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.TestEntity"));
	}

	protected TestEntity(IContext context, IMendixObject testEntityMendixObject)
	{
		if (testEntityMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.TestEntity", testEntityMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.TestEntity");

		this.testEntityMendixObject = testEntityMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TestEntity.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TestEntity initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.TestEntity.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TestEntity initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TestEntity(context, mendixObject);
	}

	public static myfirstmodule.proxies.TestEntity load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TestEntity.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final String getName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(IContext context, String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Age
	 */
	public final Long getAge()
	{
		return getAge(getContext());
	}

	/**
	 * @param context
	 * @return value of Age
	 */
	public final Long getAge(IContext context)
	{
		return (Long) getMendixObject().getValue(context, MemberNames.Age.toString());
	}

	/**
	 * Set value of Age
	 * @param age
	 */
	public final void setAge(Long age)
	{
		setAge(getContext(), age);
	}

	/**
	 * Set value of Age
	 * @param context
	 * @param age
	 */
	public final void setAge(IContext context, Long age)
	{
		getMendixObject().setValue(context, MemberNames.Age.toString(), age);
	}

	/**
	 * @return value of TestEntity_SecondEntity
	 */
	public final myfirstmodule.proxies.SecondEntity getTestEntity_SecondEntity() throws CoreException
	{
		return getTestEntity_SecondEntity(getContext());
	}

	/**
	 * @param context
	 * @return value of TestEntity_SecondEntity
	 */
	public final myfirstmodule.proxies.SecondEntity getTestEntity_SecondEntity(IContext context) throws CoreException
	{
		myfirstmodule.proxies.SecondEntity result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TestEntity_SecondEntity.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.SecondEntity.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TestEntity_SecondEntity
	 * @param testentity_secondentity
	 */
	public final void setTestEntity_SecondEntity(myfirstmodule.proxies.SecondEntity testentity_secondentity)
	{
		setTestEntity_SecondEntity(getContext(), testentity_secondentity);
	}

	/**
	 * Set value of TestEntity_SecondEntity
	 * @param context
	 * @param testentity_secondentity
	 */
	public final void setTestEntity_SecondEntity(IContext context, myfirstmodule.proxies.SecondEntity testentity_secondentity)
	{
		if (testentity_secondentity == null)
			getMendixObject().setValue(context, MemberNames.TestEntity_SecondEntity.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TestEntity_SecondEntity.toString(), testentity_secondentity.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return testEntityMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TestEntity that = (myfirstmodule.proxies.TestEntity) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.TestEntity";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
